---
title: "Schedule"
description: |
  Below is the official schedule for the event. All times are in EDT.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Opening Remarks

Time: 9:45-10:00

Speaker: KC Tsiolis (DoSS)



### Block 1: Theoretical Statistics</span>  

Chair: KC Tsiolis (DoSS)

| Time          | Title                                                                 | Speaker                      |
|---------------------|-----------------------------------------------------------------------|------------------------------|
| 10:00–10:30   | *Universality of Benign Overfitting in Binary Linear Classification* [(abstract)](abstracts.html#ichiro-hashimoto) | Ichiro Hashimoto (DoSS)      |
| 10:30–11:00   | *Regression based EM Algorithm* [(abstract)](abstracts.html#bingqing-li) | Bingqing Li (DoSS)           |





### Block 2: Applied Statistics</span>  

Chair: Yaqi Shi (DoSS)

| Time          | Title                                                                 | Speaker                             |
|--------------------|-----------------------------------------------------------------------|-------------------------------------|
| 11:15–11:45   | *Quantifying Uncertainty in Air Pollution Machine Learning Models* [(abstract)](abstracts.html#mandy-yao) | Mandy Yao (DoSS)                    |
| 11:45–12:15   | *Causal Variance Decompositions for Measuring Health Inequalities* [(abstract)](abstracts.html#lin-yu) | Lin Yu (Public Health)              |
| 12:15–12:45   | *Estimating Associations Between Cumulative Exposure and Health via Generalized Distributed Lag Non-Linear Models using Penalized Splines* [(abstract)](abstracts.html#tianyi-pan) | Tianyi Pan (Waterloo Stats & ActSci) |


### Lunch

Time: 12:45–13:30



### Block 3: Mathematical Finance and Actuarial Science</span>  

Chair: Elijah French (DoSS)

| Time          | Title                                                                 | Speaker                          |
|--------------------|-----------------------------------------------------------------------|----------------------------------|
| 13:30–14:00   | *Simplifying Complexities in IBNR Claims Count Estimation With A Bayesian GLM Approach* [(abstract)](abstracts.html#hassan-abdelrahman) | Hassan Abdelrahman (DoSS)       |
| 14:00–14:30   | *Dimension Reduction of Distributionally Robust Optimization Problems* [(abstract)](abstracts.html#brandon-tam) | Brandon Tam (DoSS)              |


### Poster Session

Time: 14:30–15:45




### Block 4: Graphical Models</span>  

Chair: Ruyi Pan (DoSS)

| Time          | Title                                                                 | Speaker                          |
|--------------------|-----------------------------------------------------------------------|----------------------------------|
| 15:45–16:15   | *Inference for Graphical Models for Extremes* [(abstract)](abstracts.html#philip-choi) | Philip Choi (DoSS)              |
| 16:15–16:45   | *Restricted Search Space Graph MCMC via Birth-Death Processes* [(abstract)](abstracts.html#morris-greenberg) | Morris Greenberg (DoSS)         |















